#!/usr/bin/env python3
"""Fill the AUTO-marked regions of the guide pages from scripts/guide_facts.py.

THE CONTRACT
------------
The two manuals — site/guide/index.html (student) and site/ops-guide/index.html
(owner) — are mostly hand-written editorial prose that must NOT be touched by a
script. Only the small, drift-prone FACTUAL regions are machine-owned, and each
is fenced with a marker pair:

    <!-- AUTO:key START · generated by scripts/guide_sync.py — do not edit by hand -->
    ...generated HTML...
    <!-- AUTO:key END -->

This script replaces ONLY the text between each pair. Everything outside the
markers is left byte-for-byte identical. If a key has no markers in a file, that
file simply doesn't get that block — so the student and owner pages can share the
generator while showing different regions.

It is idempotent: running it twice produces the same bytes. `--check` makes no
changes and exits non-zero if any region is out of date, which is how CI proves
the committed guides match the live facts (see scripts/verify_guides wiring).

WHY GENERATE THESE AND NOT OTHERS
The regions below are DERIVABLE from real system data (config.CEFR_LEVELS,
flag_registry, the curriculum files). Editorial explanations, rights/privacy
wording and tone are deliberately NOT generated — a script cannot write those
without risking exactly the "misleading information" this is meant to prevent.
"""
import argparse
import re
import sys
from datetime import date
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
GUIDE = REPO_ROOT / "site" / "guide" / "index.html"
OPS_GUIDE = REPO_ROOT / "site" / "ops-guide" / "index.html"

sys.path.insert(0, str(SCRIPT_DIR))
import guide_facts  # noqa: E402

# Per-level editorial one-liner (Arabic). The WEEKS/NAMES/EMOJI are facts pulled
# live; only this human description is authored here, kept next to the generator
# so the generated row reads naturally. Update the sentence if the teaching
# emphasis of a level changes; the numbers update themselves.
LEVEL_BLURB_AR = {
    "A1": "الأساس: الأصوات، التحيات، العائلة، الأرقام، وجمل بسيطة.",
    "A2": "الماضي، المقارنة، خطط المستقبل، والمواقف اليومية.",
    "B1": "تتعامل باستقلالية وتعبّر عن آرائك وخبراتك.",
    "B2": "طلاقة أكبر ونقاش وتفاصيل أدق.",
    "C1": "استخدام مرن وفعّال للغة في سياقات متنوعة.",
    "C2": "إتقان شبه كامل ولهجة قريبة من الأصلية.",
}


def _esc(s):
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


# ── Block renderers (each returns the inner HTML for one AUTO:key) ───────────

def block_levels_student(f):
    """The six level rows for the student guide: emoji, code+title+name_ar,
    editorial blurb, live vocab count for A1, and the live week count."""
    lv = f["levels"]
    vc = f["vocab_counts"]
    rows = []
    for x in lv:
        code = x["code"]
        blurb = LEVEL_BLURB_AR.get(code, "")
        # A1 gets the concrete "first ~N words" fact, measured from the data.
        if code == "A1":
            n = vc.get("A1")
            if n:
                blurb += f" أول <b>~{n} كلمة</b>."
        rows.append(
            f'      <div class="task-item"><div class="ico">{x["emoji"]}</div>'
            f'<div class="body"><b>{_esc(code)} — {_esc(x["title"])} / '
            f'{_esc(x["name_ar"])}</b><br>{blurb} <b>{x["weeks"]} أسبوعاً</b>.'
            f'</div></div>')
    return "\n".join(rows)


def block_levels_intro(f):
    """The '6 levels' intro sentence (level count is a fact)."""
    return (f'      <p>رحلتك في Empire على <b>{f["level_count"]} مستويات</b> '
            f'متوافقة مع الإطار الأوروبي المرجعي للغات (CEFR)، من المبتدئ (A1) '
            f'إلى الإتقان (C2). كل مستوى له منهج وأسابيع خاصة به:</p>')


def block_advancement(f):
    """Advancement thresholds — per level, from advancement_score (was a flat
    hand-typed 75%, which was wrong for A1/A2/C1/C2)."""
    lv = f["levels"]
    pairs = " · ".join(f'{x["code"]} {x["advancement_score"]}%' for x in lv)
    return (f'        🎯 <b>إزاي تترقّى؟</b> أكمل <b>كل الاختبارات الأسبوعية</b> '
            f'+ <b>مراجعة شهرية</b> ← يظهر <b>اختبار الترقية</b>. درجة النجاح '
            f'تختلف بالمستوى ({pairs}) مع <b>≥60% في كل مهارة</b> ← '
            f'<b>ترقية تلقائية!</b> 🎓 مستواك وأسبوعك دايمًا ظاهرين في '
            f'<code>!progress</code>.')


def block_levels_ops(f):
    """Level table for the ops-guide: code, title, name, weeks, vocab target,
    advancement score — all live from config.CEFR_LEVELS."""
    rows = []
    for x in f["levels"]:
        rows.append(
            f'      <div class="cmd"><div class="name"><code>{_esc(x["code"])}</code> '
            f'{x["emoji"]} {_esc(x["title"])}</div><div class="desc">'
            f'{_esc(x["name"])} · <b>{x["weeks"]}</b> أسابيع · هدف مفردات '
            f'<b>{x["vocab_target"]}</b> · درجة الترقية <b>{x["advancement_score"]}%</b>'
            f'</div></div>')
    total = f["total_weeks"]
    rows.append(
        f'      <p style="color:var(--text-muted);font-size:0.85rem">'
        f'<b>{f["level_count"]}</b> مستويات · <b>{total}</b> أسبوعاً إجمالاً. '
        f'الترقية يدوية (<code>!setlevel</code>).</p>')
    return "\n".join(rows)


def block_flags_ops(f):
    """The full feature-flag catalog for the ops-guide, grouped by initiative,
    each flag with its default state — generated from flag_registry so it can
    never be missing an initiative or list a retired flag again. Descriptions
    are the registry's own (English), which is the source of truth."""
    out = []
    for g in f["feature_flags"]:
        out.append(
            f'      <h3 style="color:var(--accent);margin:14px 0 6px">'
            f'{g["emoji"]} {_esc(g["name"])} — {_esc(g["purpose"])}</h3>')
        for fl in g["flags"]:
            dot = ('<span class="flag-on">🟢</span>' if fl["default"]
                   else '<span class="flag-off">🟠</span>')
            out.append(
                f'      <div class="cmd"><div class="name"><code>'
                f'{_esc(fl["name"])}</code> {dot}</div><div class="desc">'
                f'{_esc(fl["description"])}</div></div>')
    out.append(
        f'      <p style="color:var(--text-muted);font-size:0.85rem">'
        f'الإجمالي: <b>{f["flag_total"]}</b> عَلَمًا عبر '
        f'<b>{len(f["feature_flags"])}</b> مبادرة.</p>')
    return "\n".join(out)


def block_surfaces(f):
    """The recognised exercise/task surfaces (student + ops share this)."""
    names = ", ".join(_esc(s) for s in f["surfaces"])
    return (f'      <p>أنواع التمارين/المهام المعتمدة في النظام: '
            f'<b>{len(f["surfaces"])}</b> — <code>{names}</code>.</p>')


# key -> renderer. A file only gets the keys whose markers it contains.
BLOCKS = {
    "levels-intro": block_levels_intro,
    "levels-student": block_levels_student,
    "advancement": block_advancement,
    "levels-ops": block_levels_ops,
    "flags-ops": block_flags_ops,
    "surfaces": block_surfaces,
}

_MARKER = (
    r"(<!--\s*AUTO:{key}\s+START[^>]*-->)(.*?)(<!--\s*AUTO:{key}\s+END\s*-->)")


def _apply(html, facts):
    """Replace every AUTO:key region present in `html`. Returns (new_html,
    changed_keys, unknown_keys)."""
    changed, unknown = [], []
    present = re.findall(r"<!--\s*AUTO:([a-z0-9-]+)\s+START", html)
    for key in present:
        if key not in BLOCKS:
            unknown.append(key)
            continue
        inner = "\n" + BLOCKS[key](facts) + "\n      "
        pat = re.compile(_MARKER.format(key=re.escape(key)), re.S)

        def repl(m):
            return m.group(1) + inner + m.group(3)

        new_html, n = pat.subn(repl, html)
        if n and new_html != html:
            changed.append(key)
        html = new_html
    return html, changed, unknown


def sync_file(path, facts, check):
    if not path.exists():
        return [], []
    original = path.read_text(encoding="utf-8")
    updated, changed, unknown = _apply(original, facts)
    # Bump the build marker date only when something actually changed, so a
    # no-op run stays a no-op (and the diff stays clean).
    if changed and not check:
        updated = re.sub(
            r"(guide-build:\s*[\w-]+\s*\()\d{4}-\d{2}-\d{2}(\))",
            lambda m: m.group(1) + date.today().isoformat() + m.group(2),
            updated, count=1)
    if updated != original and not check:
        path.write_text(updated, encoding="utf-8")
    return changed, unknown


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="make no changes; exit 1 if any AUTO region is stale")
    args = ap.parse_args()

    try:
        facts = guide_facts.all_facts()
    except guide_facts.FactsUnavailable as e:
        print(f"::warning::guide sync skipped — {e}")
        return 0

    stale = False
    for label, path in (("student /guide", GUIDE), ("owner /ops-guide", OPS_GUIDE)):
        changed, unknown = sync_file(path, facts, args.check)
        for k in unknown:
            print(f"::warning::{label}: AUTO:{k} has markers but no renderer")
        if args.check and changed:
            stale = True
            print(f"::error::{label} is STALE — AUTO region(s) out of date: "
                  f"{', '.join(changed)}. Run: python3 scripts/guide_sync.py")
        elif changed:
            print(f"  {label}: updated {', '.join(changed)}")
        else:
            print(f"  {label}: up to date")

    if args.check and stale:
        return 1
    if not args.check:
        print("  guides synced.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
